"""empty message

Revision ID: 308cbb6decf4
Revises: 
Create Date: 2019-02-03 21:16:08.166441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '308cbb6decf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CSdb_addn', 'InChI_string')
    op.drop_column('CSdb_addn', 'index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CSdb_addn', sa.Column('index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('CSdb_addn', sa.Column('InChI_string', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
